### ISSUE TITLE
Current stable executable for Windows, states a "Newer version of Windows" is needed when run on Windows XP

### ISSUE THREAD

**Issue by afarlie** [valentina-project/vpo2-saved#752]
I am placing this in the issue tracker, as given some discussions on IRC about a related issue with some other software, I was told such issues were typically to do with the build environment used to create the executable, and that with an appropriate build environment and some modification into how a specific aspect of calling something in the Qt libary was performed, it may be possible for an experienced developer to get a build of the program that works on Windows XP.  It would be appreciated if a special "support" build was considered, that it ran on older OS like XP, if the effort involved is minimal. 

However, I am more than willing to accept that as Qt and other libararies have in recent versions dropped support for older OS (not just XP, but certain older distributions of various "free" OS ) it may not be possible for this to occur.

I would also strongly suggest alongside the current branches, creating an "extended support release" branch  for the longer term.  The purpose of an ESR build would be to have one in which only "critical" bugs were fixed directly, and in which new features were not added until some time after they had been proven in a "stable" release.  An ESR would thus be even more stable than a stable release, something which may be appreciated by some users.

Thanks for putting the repository on GitHub BTW.

**Comment by slspencer** [comment]
Yes, we used to support XP but when Qt dropped its support then it was no
longer possible.

Yeah, when we actually have a v1.0.0 release, we will begin create a long
term release as this has become 'best practice' in the industry. It implies
that customers can rely on the software to 'stick around' for a long time.

And you're welcome about the github move. I wish we could have done this a
long time ago.

**Comment by afarlie** [comment]
Thanks.   This issue should be closed as an "As Designed" then.
